name: "Tests"

on:
  - "push"
  - "pull_request"

jobs:
  tests:

    runs-on: "ubuntu-latest"
    continue-on-error: "${{ matrix.continue-on-error }}"
    strategy:
      matrix:
        include:
         - php-versions: "8.1"
           continue-on-error: false
         - php-versions: "8.2"
           continue-on-error: false
         - php-versions: "8.3"
           continue-on-error: true

    steps:
    - uses: "actions/checkout@v3"

    - name: "Cache Composer packages"
      id: "composer-cache"
      uses: "actions/cache@v2"
      with:
        path: "vendor"
        key: "${{ runner.os }}-php-${{ matrix.php-versions }}-${{ hashFiles('**/composer.lock') }}"
        restore-keys: |
          "${{ runner.os }}-php-"

    - name: "Setup PHP Action"
      uses: "shivammathur/setup-php@v2"
      with:
        php-version: "${{ matrix.php-versions }}"
        extensions: "intl, xdebug"

    - name: "Install dependencies"
      if: steps.composer-cache.outputs.cache-hit != 'true' && matrix.php-versions != '8.3'
      run: "composer install --prefer-dist --no-progress"

    - name: "Install dependencies"
      if: steps.composer-cache.outputs.cache-hit != 'true' && matrix.php-versions == '8.3'
      run: "composer install --prefer-dist --no-progress --ignore-platform-reqs"

    - name: "Unit + Integration"
      run: "vendor/bin/phpunit"

    - name: "Mutation tests"
      run: "vendor/bin/infection --min-msi=98 --no-progress --threads=5"
